### ISSUE TITLE
MersenneTwister19937 is not defined

### ISSUE THREAD

**Issue by hashbackspace** [ckknight/random-js#34]
Code:- 

const { Random } = require("random-js");

const random = new Random(MersenneTwister19937.autoSeed());

var value = random.integer(1, 100);
console.log(value)

Error:- 

ReferenceError: MersenneTwister19937 is not defined
    at Object.<anonymous> (D:\mersenneTwister\init.js:4:27)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

Any idea what i am doing wrong ?

**Comment by hashbackspace** [comment]
Sorry, I found the issue.

If any one face this issue you may have to do this:- 

const { Random, MersenneTwister19937 } = require("random-js");
